repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
  - name: vault
    namespace: default
    chart: https://github.com/hashicorp/vault-helm/archive/v0.3.1.tar.gz
    values:
      - vault.yaml
    wait: true
  - name: nginx-ingress-controller
    namespace: default
    chart: stable/nginx-ingress
    values:
      - controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
