kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 worker
nodes:
# the control plane node config
- role: control-plane
# the worker node config
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
